[params]
    [head]
        [head.meta]
            [head.meta.generic]
                title = "Software for the management of marinas"
                description = "InfoMarina is a complete IT solution for the management of marinas and yacht clubs."
            [head.meta.og]
                type = "website"
            [head.meta.twitter]
                card = "summary"
    [menu]
        [[menu.header]]
            weight = 1
            name = "Home"
            url = "#home"
        [[menu.header]]
            weight = 2
            name = "Modules"
            url = "#features"
        [[menu.header]]
            weight = 3
            name = "Testimonials"
            url = "#testimonials"
        [[menu.header]]
            weight = 4
            name = "Clients"
            url = "#clients"
        [[menu.header]]
            weight = 5
            name = "Pricing"
            url = "#package"
        [[menu.header]]
            weight = 6
            name = "Contact"
            url = "#contact"
        [[menu.header]]
            weight = 7
            name = "Français"
            url = "/"
    [hero]
        enable = true
        title = "InfoMarina"
        subtitle = "Complete software solution for managing marinas and yacht clubs of all sizes"
        bgImage = "http://demo.themefisher.com/airspace-hugo/img/slider-bg.jpg"
        btnText = "Come aboard with us!"
        url = "#"
    [features]
        enable = true
        perRows = 2
    [testimonials]
        enable = true
        title = "Testimonials"
        lead = "We have worked with many customers and we always like to hear that they are happy and satisfied with this cooperation. Look what our customers have said about us."
    [clients]
        enable = true
        title = "Our Clients"
        lead = "Our main goal in everything we do is for the satisfaction of our customers."
    [contact]
        enable = true
        title = "Contact Us"
        lead = "You want to know more? Give us a call! We will be happy to answer you."
        address = "31 des Alouettes, Sainte-Anne-des-Lacs <br/>Québec, Canada J0R 1B0"
        phone =  "Toll-free: +1-888-824-7474"
        email =  "info@infomarina.ca"
        form_email = "info@infomarina.ca"
        form_email_placeholder = "Your Email"
        form_name_placeholder = "Your Name"
        form_message_placeholder = "Your Message"
        form_submit_text = "Send"
    [packages]
        enable = true
        title = "Our Pricings"
        lead = "Please note that all our rates are based on the number of licenses and the number of platforms in your location."
    [changelog]
        default_added_label = "Added"
        default_fixed_label = "Fixed"
        download_label = "Download"
        no_download_label = "Not Available"
        version_prefix_label = "InfoMarina version "
