[params]
    [menu]
        [[menu.header]]
            weight = 1
            name = "Accueil"
            url = "#home"
        [[menu.header]]
            weight = 2
            name = "Modules"
            url = "#features"
        [[menu.header]]
            weight = 3
            name = "Témoignages"
            url = "#testimonials"
        [[menu.header]]
            weight = 4
            name = "Clients"
            url = "#clients"
        [[menu.header]]
            weight = 5
            name = "Forfaits"
            url = "#pricing"
        [[menu.header]]
            weight = 6
            name = "Contact"
            url = "#contact"
        [[menu.header]]
            weight = 7
            name = "English"
            url = "/en"
    [slider]
        enable = true
        title = "InfoMarina"
        subtitle = "Solution logicielle complète pour la gestion des marinas, ports de plaisance et yachts club de toutes tailles."
        bgImage = "http://demo.themefisher.com/airspace-hugo/img/slider-bg.jpg"
        btnText = "Amarrez-vous à nous!"
        url = "#"
    [features]
        enable = true
        perRows = 2
    [testimonials]
        enable = true
        title = "Témoignages"
        lead = "Nous avons travaillé avec de nombreux clients et nous aimons toujours entendre dire qu'ils sont heureux et satisfaits de cette coopération. Regardez ce que nos clients ont dit de nous."
    [clients]
        enable = true
        title = "Nos Clients"
        lead = "Notre principal objectif dans tout ce que nous faisons est la satisfaction de nos clients"
    [contact]
        enable = true
        title = "Nous Contactez"
        lead = "Vous voulez en savoir plus? Donnez-nous un coup de fil! Nous serons heureux de vous répondre."
        address = "31 des Alouettes, Sainte-Anne-des-Lacs <br/>Québec, Canada J0R 1B0"
        phone =  "Sans frais: +1-888-824-7474"
        email =  "info@infomarina.ca"
        form_email = "info@infomarina.ca"
        form_email_placeholder = "Votre Courriel"
        form_name_placeholder = "Votre Nom"
        form_message_placeholder = "Votre Message"
        form_submit_text = "Envoyer"
    [pricings]
        enable = true
        title = "Nos Forfaits"
        lead = "Veuillez noter que tous nos tarifs sont fonction du nombre de licence et du nombre de quai de votre location."
